### ISSUE TITLE
Give more information about yarn changeset

### ISSUE THREAD

**Issue by alexbakers** [smartcontractkit/external-adapters-js#2293]
Hello, friends.

I created an adapter, 

```bash
⚠️ NOTICE: Adapter changes must also have a changeset. Generate a changeset with 'yarn changeset' and include it in your commit.
```

but I can't run the command:

```bash
$ yarn changeset                  
🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?
🦋  error     at getDivergedCommit (/Users/Jack/Developer/novaposhta-adapter/external-adapters-js/.yarn/cache/@changesets-git-npm-1.5.0-2b3630ea97-7208d5bff9.zip/node_modules/@changesets/git/dist/git.cjs.dev.js:67:11)
🦋  error     at async getChangedFilesSince (/Users/Jack/Developer/novaposhta-adapter/external-adapters-js/.yarn/cache/@changesets-git-npm-1.5.0-2b3630ea97-7208d5bff9.zip/node_modules/@changesets/git/dist/git.cjs.dev.js:199:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/Users/Jack/Developer/novaposhta-adapter/external-adapters-js/.yarn/cache/@changesets-git-npm-1.5.0-2b3630ea97-7208d5bff9.zip/node_modules/@changesets/git/dist/git.cjs.dev.js:239:24)
🦋  error     at async add (/Users/Jack/Developer/novaposhta-adapter/external-adapters-js/.yarn/cache/@changesets-cli-npm-2.18.1-b00d4d209e-d893c5144c.zip/node_modules/@changesets/cli/dist/cli.cjs.dev.js:462:29)
🦋  error     at async run$2 (/Users/Jack/Developer/novaposhta-adapter/external-adapters-js/.yarn/cache/@changesets-cli-npm-2.18.1-b00d4d209e-d893c5144c.zip/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1188:5)
```

**Comment by eddiejhong** [comment]
Hey Alex, may you please provide steps to repro this issue? If you have a PR for this new adapter, may you also please share a link to it?

**Comment by eddiejhong** [comment]
The yarn changeset command sometimes throws an error about the "master" branch, which may be resolved by checkout out "master" and pulling it.

**Comment by eddiejhong** [comment]
I looked into this briefly with @boxhock and it seems like `.changeset/config.json` may be misconfigured to use `"baseBranch": "master",` instead of `"baseBranch": "develop",`

**Comment by alexbakers** [comment]
Thanks for the quick response.

https://github.com/smartcontractkit/external-adapters-js/pull/2294

Do I need to fix something?

**Comment by boxhock** [comment]
Hi @alexbakers,

No need for you to fix anything.
To get changesets working, try `git checkout master && git pull`, then check out your branch again and run `yarn changeset`.

**Comment by mxiao-cll** [comment]
Please re-open if this is still relevent
