### ISSUE TITLE
Make build failing

### ISSUE THREAD

**Issue by karzak** [smartcontractkit/external-adapters-js#26]
After installing using 
```
yarn
```

at the top level, I ran `make build coingecko` and am getting
```
make build coingecko
yarn ncc build  -o /dist
yarn run v1.22.4
$ /Users/kjd/go/src/github.com/smartcontractkit/external-adapters-js/node_modules/.bin/ncc build -o /dist
{ Error: Cannot find module '/Users/kjd/go/src/github.com/smartcontractkit/external-adapters-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at resolve (internal/modules/cjs/helpers.js:33:19)
    at runCmd (evalmachine.<anonymous>:1:47259)
    at Object.819 (evalmachine.<anonymous>:1:44241)
    at __webpack_require__ (evalmachine.<anonymous>:1:216)
    at startup (evalmachine.<anonymous>:1:353)
    at module.exports.8 (evalmachine.<anonymous>:1:385)
    at evalmachine.<anonymous>:1:395
    at Object.<anonymous> (/Users/kjd/go/src/github.com/smartcontractkit/external-adapters-js/node_modules/@zeit/ncc/dist/ncc/cli.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build] Error 1
```

Seems to be happening for all the adapters I tried.

**Comment by thodges-gh** [comment]
@karzak The syntax is:
```
make build adapter=coingecko
```
