### ISSUE TITLE
Issue running CoinMarketCap adapter

### ISSUE THREAD

**Issue by daweth** [smartcontractkit/external-adapters-js#3134]
on `yarn generate:docker-compose` I get

```
/root/external-adapters-js/packages/scripts/src/docker-build/lib.ts:60
                environment: Object.entries(flattenedSchemasByLocation[next.location]?.schema ?? {}).map(([k, v]) => {
                                                                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/root/external-adapters-js/.yarn/__virtual__/ts-node-virtual-7b84b52de7/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at require$$0.Module._extensions..js (/root/external-adapters-js/.pnp.cjs:49590:33)
    at Object.require.extensions.<computed> [as .ts] (/root/external-adapters-js/.yarn/__virtual__/ts-node-virtual-7b84b52de7/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/index.ts:1621:12)
 ```

on `yarn start` I get

```
/root/external-adapters-js/.yarn/cache/@chainlink-external-adapter-framework-npm-0.33.2-c63d4f8e01-e6de81d753.zip/node_modules/@chainlink/external-adapter-framework/index.js:69
            api?.addHook('onClose', async () => {
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require$$0.Module._extensions..js (/root/external-adapters-js/.pnp.cjs:49590:33)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.require$$0.Module._load (/root/external-adapters-js/.pnp.cjs:49427:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/external-adapters-js/packages/sources/coinmarketcap/dist/index.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    ```

**Comment by karen-stepanyan** [comment]
Hello @daweth . What is the node version ?

**Comment by mxiao-cll** [comment]
Feel free to re-open if this still exists
