### ISSUE TITLE
SyntaxError in bootstrap on calling yarn start

### ISSUE THREAD

**Issue by jaysharm** [smartcontractkit/external-adapters-js#665]
/Users/jamessharman/Projects/chainlink/external-adapters-js/packages/core/bootstrap/dist/lib/cache/index.js:101
            isFromWs: !!adapterRequest.debug?.ws,
                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.external_module_.Module._load (/Users/jamessharman/Projects/chainlink/external-adapters-js/.pnp.js:34112:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/jamessharman/Projects/chainlink/external-adapters-js/packages/core/bootstrap/dist/index.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

**Comment by jaysharm** [comment]
Hi All, I'm trying to write a new chainlink extension adapter but I can't test it locally as `yarn start` fails with this bootstrap syntax error.  Has anyone seen this before?

**Comment by jaysharm** [comment]
An ancient node version was being used... Disregard,,,
